---
- name: Install and configure Pi-hole and Unbound
  hosts: your_hosts
  gather_facts: yes
  become: yes

  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary packages
      apt:
        name:
          - curl
          - dnsutils
          - netcat
        state: latest

    - name: Install Pi-hole
      shell: curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended
      args:
        creates: /etc/.pihole

    - name: Install Unbound
      apt:
        name: unbound
        state: latest

    - name: Remove Unbound default configuration file
      file:
        path: /etc/unbound/unbound.conf
        state: absent

    - name: Create Unbound configuration file
      copy:
        content: |
          server:
            verbosity: 0
            interface: 127.0.0.1
            port: 5335
            do-ip4: yes
            do-udp: yes
            do-tcp: yes
            do-ip6: no
            prefer-ip6: no
            harden-glue: yes
            harden-dnssec-stripped: yes
            use-caps-for-id: no
            edns-buffer-size: 1232
            prefetch: yes
            num-threads: 1
            so-rcvbuf: 1m
            private-address: 192.168.0.0/16
            private-address: 169.254.0.0/16
            private-address: 172.16.0.0/12
            private-address: 10.0.0.0/8
            private-address: fd00::/8
            private-address: fe80::/10
        dest: /etc/unbound/unbound.conf.d/pi-hole.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Unbound
      systemd:
        name: unbound
        state: restarted
        enabled: yes

    - name: Set Unbound as the upstream DNS server for Pi-hole
      ansible.builtin.lineinfile:
        path: /etc/pihole/setupVars.conf
        regexp: '^PIHOLE_DNS='
        line: 'PIHOLE_DNS=127.0.0.1#5335'

    - name: Restart pihole-FTL service
      ansible.builtin.systemd:
        state: restarted
        name: pihole-FTL
...
